[Interface]
Address = 10.7.0.2/24, fddd:2c4:2c4:2c4::2/64
DNS = 8.8.8.8, 8.8.4.4
PrivateKey = EJ7bVjFNveD0H/2vDYSb0dxZxxFyYlJKzRvsFdwCm1Y=

[Peer]
PublicKey = XoDIljspw9N7xJ2YxnY21pVUYxgjedlGR6mdxJW9vTw=
PresharedKey = WDmMxLkxPlrXFYJEjXPBVkKJznz6CBlSkzfOhiuu+Tw=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 64.188.112.148:51820
PersistentKeepalive = 25
